workspace:
  base: /test
  path: epoetry-client

services:
  web:
    image: fpfis/httpd-php-dev:${PHP_VERSION=7.1}
    environment:
      - DOCUMENT_ROOT=/test/epoetry-client

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-dev:${PHP_VERSION=7.1}
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  composer-install-lowest:
    group: post-prepare
    image: fpfis/httpd-php-dev:${PHP_VERSION=7.1}
    volumes:
      - /cache:/cache
    commands:
      # Perform a composer install to work around an issue where an update
      # without a lock file present affects the resolving of dependencies.
      # Todo: Remove the `composer install` when the composer bug is fixed.
      # Ref. https://github.com/composer/composer/issues/7542
      # Ref. https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1234
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  grumphp:
    group: test
    image: fpfis/httpd-php-dev:${PHP_VERSION=7.1}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-dev:${PHP_VERSION=7.1}
    commands:
      - ./vendor/bin/phpunit

matrix:
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  PHP_VERSION:
    - 7.1
    - 7.2
