name: ci
on: [push, pull_request]

jobs:
  automated-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["8.3"]
        composer_command: ["composer install"]
    env:
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Build dependencies
        run: docker-compose exec -T php ${{ matrix.composer_command }}

#      - name: Run tests
#        run: docker-compose exec -T php ./vendor/bin/phpunit
      # While porting to 3.x run each test suite separately.
      # We will remove this one the job is done.
      - name: CodeGenerator
        run: "docker-compose exec -T php ./vendor/bin/phpunit --testsuite CodeGenerator"
      - name: ExtSoapEngine
        run: "docker-compose exec -T php ./vendor/bin/phpunit --testsuite ExtSoapEngine"
      - name: Notification
        run: "docker-compose exec -T php ./vendor/bin/phpunit --testsuite Notification"
      - name: Request
        run: "docker-compose exec -T php ./vendor/bin/phpunit --testsuite Request"
      - name: RequestClientFactoryTest
        run: "docker-compose exec -T php ./vendor/bin/phpunit --testsuite RequestClientFactoryTest"
      - name: SerializerTest
        run: "docker-compose exec -T php ./vendor/bin/phpunit --testsuite SerializerTest"

# We will run codesniffer at the end of our refactoring effort.
#  code-sniffer:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        php_version: ["8.3"]
#    env:
#      PHP_VERSION: ${{ matrix.php_version }}
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v2
#
#      - name: Install Docker Compose
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y docker-compose
#
#      - name: Start services with Docker Compose
#        run: docker-compose up -d
#
#      - name: Install dependencies
#        run: docker-compose exec -T php composer install
#
#      - name: Run code sniffer
#        run: docker-compose exec -T php ./vendor/bin/grumphp run